### ISSUE TITLE
ERROR: Unknown error occured. Are you using the right format?

### ISSUE THREAD

**Issue by anttxt** [rngchan/sun-moon-rng#18] opened 2017-01-22 00:58 UTC
There was an error processing your config file:
ERROR: Unknown error occurred. Are you using the right format?

this error occurs whenever I run the rng-abuse.py 
I have made sure everything is correct in my file and I've made several changed in case I imputed something in wrong (I'm not a skilled coder nor do I know a lot about python). 
I included my config.txt because I did something wrong. thank you!
[config.txt](https://github.com/rngchan/sun-moon-rng/files/721608/config.txt)

EDIT i added the 0x's before the seed codes but it's still not working. also i do no know my TSV so i just used the one the config_example.txt came with. could this cause a problem?:
======================
    RNG PARAMETERS    
======================
STATUS 3: 0x88FAb64B
STATUS 2: 0x2C89E71F
STATUS 1: 0x4E21F594
STATUS 0: 0x4A91FB34
TSV: 1010
ESV: []

**Comment by rngchan** [comment] 2017-01-23 16:17
That doesn't seem to be the issue. The problem is that you have two line breaks between the RNG Parameters and Other Options sections. The script expects a very specific format with only one line break between sections, so by adding an extra one it's reading lines wrong. I'm attaching a fixed version of your config file, and closing this for now. Feel free to reopen if you have further issues.
[config.txt](https://github.com/rngchan/sun-moon-rng/files/724246/config.txt)

**Closed as completed by rngchan** 2017-01-23 16:17 UTC
